apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config-init
  namespace: {{ .Release.namespace }}
data:
  VAULT_REQUEST: |{{ .Values.vaultRetrieve.env.vaultRequest | nindent 4 }}
  MOUNT_PATH: "{{ .Values.vaultRetrieve.env.mountPath }}"
  SPRING_CLOUD_VAULT_AUTHENTICATION: "{{ .Values.vaultRetrieve.env.vaultAuth }}"
  SPRING_CLOUD_VAULT_URI: "{{ .Values.vaultRetrieve.env.vaultUri }}"
