{{- if .Values.redis.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-redis-service
  namespace: {{ .Release.namespace }}
spec:
  selector:
    app: {{ .Chart.Name }}-redis
  ports:
  - protocol: TCP
    port: {{ .Values.redis.service.port }}
    targetPort: {{ .Values.redis.service.port }}
  type: {{ .Values.redis.service.type }}
{{- end }}
